From 63ab1d5d52aa2e4bd77e4bdcec9cb343712dfa9d Mon Sep 17 00:00:00 2001 Subject: [PATCH] irqd: fix use of va_list on ARM
As the irqd code cant be compiled for arm because va_list cant be NULL.

<quote>
log.c: In function 'id_bug':
log.c:76:2: error: incompatible type for argument 4 of 'id_fail_va'
log.c:68:1: note: expected 'va_list' but argument is of type 'void *'
log.c: In function 'id_oom':
log.c:83:2: error: incompatible type for argument 4 of 'id_fail_va'
log.c:68:1: note: expected 'va_list' but argument is of type 'void *'
make: *** [log.o] Error 1
</quote>

Author: Joop Boonen <joop.boonen@opensuse.org>
Signed-off-by: Holger Eitzenberger <holger@eitzenberger.org>